export { default as About} from './About'
export { default as Contact} from './Contact'
export { default as Experiences} from './Experiences'
export { default as Goals} from './Goals'
export { default as Home} from './Home'
export { default as SoftSkills} from './SoftSkills'
export { default as TechSkills} from './TechSkills'